on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    name: Static Analysis P${{ matrix.php-versions }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php-versions: ['8.2']
        dependency-version: [prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php-versions }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Run PHP Stan check
        run: vendor/bin/phpstan analyse

      - name: Run Pint check
        run: vendor/bin/pint