on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    name: Tests P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php-versions: ['8.1', '8.2']
        laravel: ['10.*', '9.*']
        dependency-version: [prefer-stable]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php-versions }}-L${{ matrix.laravel }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none

    - name: Require Laravel Version
      run: >
        composer require
        "laravel/framework:${{ matrix.laravel }}"
        --no-interaction --no-update

    - name: Install Composer dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

    - name: Integration Tests
      run: php ./vendor/bin/pest